# Generated by Django 4.0.4 on 2022-05-29 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drawing',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
