# Generated by Django 4.0.4 on 2022-05-29 19:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_alter_drawing_submitted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drawing',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='drawing',
            name='votes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
